insert into Items 
(item_name, status, availability, nature) 
    VALUES
('coin', 'free', 'yes', 'currency'),
('diamond_gem', 'premium', 'no', 'currency'),
('jump_boost', 'free', 'yes', 'booster'),
('ghost_mask', 'special', 'upcoming', 'accessory'),
('star_chip', 'free', 'yes', 'currency'),
('santa_hat', 'special', 'live event', 'accessory'),
('rocket_blaster', 'premium', 'no', 'booster'),
('lava_hammer', 'special', 'upcoming', 'epic_suit'),
('speed_dash', 'free', 'yes', 'booster'),
('pumpkin', 'special', 'live event', 'collectible'),
('energy_crystal', 'free', 'yes', 'currency'),
('phoenix_armor', 'premium', 'no', 'epic_suit'),
('shield_bubble', 'free', 'yes', 'booster'),
('pixel_hat', 'free', 'yes', 'accessory'),
('time_orb', 'special', 'upcoming', 'booster'),
('bouncy_ball', 'free', 'yes', 'collectible'),
('crescent_moon', 'special', 'live event', 'collectible'),
('neon_suit', 'free', 'yes', 'epic_suit'),
('runner_avatar', 'free', 'yes', 'character'),
('fireworks_rocket', 'special', 'live event', 'booster'),
('speedy_sam', 'free', 'yes', 'character'),
('coin_bag', 'free', 'yes', 'collectible'),
('jumpster', 'free', 'yes', 'character'),
('golden_cape', 'premium', 'no', 'legendary_suit'),
('star_orb', 'premium', 'no', 'collectible'),
('slime_blob', 'free', 'yes', 'obstacle') ,
('gold_coin', 'premium', 'yes', 'currency'),
('gemstone', 'premium', 'yes', 'currency'),
('silver_note', 'premium', 'yes', 'currency');